"""document table created

Revision ID: b6175b060f8c
Revises: 278817b42876
Create Date: 2026-08-24 13:19:53.853648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b6175b060f8c'
down_revision: Union[str, Sequence[str], None] = '278817b42876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('document_number', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('document_type', sa.Enum('PASSAPORTE', 'TITULO_RESIDENCIA', 'COMPROVATIVO_MORADA', 'BI', name='documenttype'), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='documentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    # ### end Alembic commands ###
