"""remittance table added

Revision ID: f39623e69dfc
Revises: b6175b060f8c
Create Date: 2026-08-25 14:36:31.478162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f39623e69dfc'
down_revision: Union[str, Sequence[str], None] = 'b6175b060f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remittance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('service_fee_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_converted', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source_coin', sa.Enum('EUR', 'AOA', name='allowedcoins'), nullable=False),
    sa.Column('target_coin', sa.Enum('EUR', 'AOA', name='allowedcoins'), nullable=False),
    sa.Column('service_fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('recipient_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('recipient_account_iban', sqlmodel.sql.sqltypes.AutoString(length=35), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SENT', 'REJECTED', name='remittancestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remittance')
    # ### end Alembic commands ###
